enum ContentType {
  beautifulWords,
  phrases,
  idioms,
  proverbs,
  literaryExtracts,
  regionalDialects,
  literatureRecommendations,
  exerciseFillInTheBlank,
  exerciseMultipleChoice,
  exerciseMatchingGame,
  exerciseListeningComprehension,
  exerciseTrueFalse,
  exerciseWordAssociation,
}
